### ISSUE TITLE
Can't Install v14 helpdesk_mgmt

### ISSUE THREAD

**Issue by Royedc4** [OCA/helpdesk#498] opened 2023-08-05 16:59 UTC
## Module
[helpdesk_mgmt](https://github.com/OCA/helpdesk/tree/14.0/helpdesk_mgmt)

## Describe the bug
When trying to install in EE v14 It shows the following error: 

```
odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 198, in load_module_graph
    registry.setup_models(cr)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 276, in setup_models
    model._setup_fields()
  File "/home/odoo/src/odoo/odoo/models.py", line 2849, in _setup_fields
    field.setup_full(self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 418, in setup_full
    self._setup_regular_full(model)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3128, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'project_id'
2023-08-05 16:24:56,703 4 ERROR plustteam-c13-compresoresservicios-feature-r-helpdes-9221773 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 478, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 198, in load_module_graph
    registry.setup_models(cr)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 276, in setup_models
    model._setup_fields()
  File "/home/odoo/src/odoo/odoo/models.py", line 2849, in _setup_fields
    field.setup_full(self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 418, in setup_full
    self._setup_regular_full(model)
  File "/home/odoo/src/odoo/odoo/fields.py", line 3128, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'project_id'
```

## To Reproduce
**Affected versions**: v14

1. Install Module

**Expected behavior**
It should install

**Additional context**
It seems This module is a redo (no inherit, of base helpdesk) Maybe this is why it generates these errors? I'm confused.

**Comment by pedrobaeza** [comment] 2023-08-06 11:22
I'm afraid you have your DB a bit messed or not installing correctly the module, but it's not a bug in the module, so closing.

**Closed as completed by pedrobaeza** 2023-08-06 11:22 UTC
Labels: bug
